apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kangaroo
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      nodeSelector:
        kubernetes.io/role: node
      containers:
      - name: dummy-logsink
        image: docker.io/stevenacoffman/dummy-logsink@sha256:e8fa3862b87a415fc84daa23c85c695a54e95fe53192d0de239dc96322fb3eda
        env:
        - name: DELAY
          value: "0"
        - name: PORT
          value: "4000"
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 0.2
            memory: "10Mi"
          limits:
            memory: "20Mi"
      - name: other-dummy-logsink
        image: docker.io/stevenacoffman/dummy-logsink@sha256:e8fa3862b87a415fc84daa23c85c695a54e95fe53192d0de239dc96322fb3eda
        env:
        - name: DELAY
          value: "0"
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 0.2
            memory: "10Mi"
          limits:
            memory: "20Mi"
      - name: fluent-bit
        image: edsiper/fluent-bit-0.13-next:0.17-5@sha256:b74a30e3ec7308006e6dbe00c45c159e06bad66f263c11cc62cdb0cf868547fd
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        readinessProbe:
          httpGet:
            path: /api/v1/metrics/prometheus
            port: 2020
        livenessProbe:
          httpGet:
            path: /
            port: 2020
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 260Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
